import { act } from 'react';
import { createRoot } from 'react-dom/client';
import { expect, it, vi } from 'vitest';
import { ReadingLibraryNavigation } from './ReadingLibraryView';
import type { useReadingLibrary } from './useReadingLibrary';

it('keeps ten files in a dismissible popup with stable ordering across switches', async () => {
  (globalThis as any).IS_REACT_ACT_ENVIRONMENT = true;
  const host = document.createElement('div'); document.body.append(host); const root = createRoot(host);
  const entries = Array.from({length:10}, (_,i)=>({id:String(i), filename:`文章${i+1}.md`,path:`/test/${i}.md`}));
  const open=vi.fn(), choose=vi.fn();
  const library={recoveries:[],ready:true,list:{entries:[...entries].reverse(),warnings:[],nativePicker:true},entry:{id:'0',workspace:{document:{filename:'文章1.md'}}},open,choose} as unknown as ReturnType<typeof useReadingLibrary>;
  const render=()=>root.render(<ReadingLibraryNavigation library={library} importCopy={vi.fn()} />);
  await act(async()=>render());
  expect(host.querySelector('.library-items')).toBeNull();
  const trigger=host.querySelector<HTMLButtonElement>('.library-current')!;
  await act(async()=>trigger.click());
  const writeText=vi.fn().mockResolvedValue(undefined);
  Object.defineProperty(navigator, 'clipboard', {configurable:true,value:{writeText}});
  await act(async()=>(host.querySelector('.library-copy-path') as HTMLButtonElement).click());
  expect(writeText).toHaveBeenCalledWith('/test/0.md');
  expect(host.textContent).toContain('路径已复制');
  expect(open).not.toHaveBeenCalled();
  writeText.mockRejectedValueOnce(new Error('denied'));
  await act(async()=>(host.querySelectorAll('.library-copy-path')[1] as HTMLButtonElement).click());
  expect(host.textContent).toContain('复制失败，请选中路径手动复制');
  const order=()=>[...host.querySelectorAll('.library-open')].map(e=>e.textContent);
  expect(order()).toEqual(entries.map(e=>e.filename));
  expect(host.querySelector('.library-path-tip')).toBeNull();expect(host.querySelector('.library-current')?.getAttribute('title')).toBe('文章1.md');
  await act(async()=>(host.querySelectorAll('.library-open')[2] as HTMLElement).click());
  expect(open).toHaveBeenCalledWith('2');expect(host.querySelector('.library-items')).toBeNull();
  library.list.entries.reverse();
  await act(async()=>render());await act(async()=>trigger.click());
  expect(order()).toEqual(entries.map(e=>e.filename));
  await act(async()=>trigger.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})));
  expect(host.querySelector('.library-items')).toBeNull();
  expect(document.activeElement).toBe(trigger);
  await act(async()=>root.unmount());host.remove();
});
